feat: install eslint and add .eslintrc.json file
ShSato4JPN/world-of-zono pull request #14
Opened 2022-11-02 16:43 UTC by ShSato4JPN

close #13

2022-11-02 16:46 UTC, piro0919 requested changes

2022-11-02 16:46 UTC, piro0919 commented on .eslintrc.json
> +  "ignorePatterns": ["/node_modules/", "/dist/"],
[imo]

今回のケースでは最適な設定でない気がしますね。 👀

2022-11-02 17:19 UTC, ShSato4JPN commented on .eslintrc.json
> +  "ignorePatterns": ["/node_modules/", "/dist/"],
@piro0919 

```
  "parser": "@typescript-eslint/parser",
  "parserOptions": { "project": ["./tsconfig.json"] },
```
typescript を解析するには parser が必要で、その詳細設定として tsconfig.json をオプションで指定する必要があると認識しております。
勉強不足で申し訳ないのですが、こちらの設定が不要な理由が分かりません🤯
公式ドキュメントの例でも実装されていました。（[ESlint](https://eslint.org/docs/latest/user-guide/configuring/configuration-files)）
```
  "overrides": [],
```
使用していないのであれば記述するべきではありませんでした。
```
  "ignorePatterns": ["/node_modules/", "/dist/"]
```
[ESlint-Ignoring Code](https://eslint.org/docs/latest/user-guide/configuring/ignoring-code) を読んだところ、`.eslintignore` ファイルを作成することで lint 対象外のファイル・フォルダを指定できることが分かりました。
なので、ignorePatterns で記述するのは間違っていますね...。
また、dist フォルダは本プロジェクトで使用するか分からないため、現段階では設定に含めるべきではありませんでした。

2022-11-03 14:02 UTC, ShSato4JPN commented
@piro0919 

[f30ec4f](https://github.com/ShSato4JPN/world-of-zono/pull/14/commits/f30ec4f0426becb4e19b8120628661541c3af6e6)
指摘箇所を修正いたしました。
お手隙の際にご確認よろしくお願いいたします。

2022-11-03 16:27 UTC, piro0919 approved these changes
LGTM 👍

2022-11-03 16:33 UTC, ShSato4JPN commented
@piro0919 

Thank you for your approval.

2022-11-03 16:33 UTC, merged