feat: install stylelint and create .stylelintrc.json
ShSato4JPN/world-of-zono pull request #19
Opened 2022-11-09 15:24 UTC by ShSato4JPN

close #18

2022-11-09 15:40 UTC, piro0919 requested changes

2022-11-09 15:40 UTC, piro0919 commented on .stylelintrc.json
> +    "stylelint-config-standard-scss",
[must]

ここ 2 つともいりましたっけ？ 👀 
公式に記述があった気がします。

2022-11-09 15:40 UTC, piro0919 commented on .stylelintrc.json
> +    "stylelint-config-prettier-scssx`"
[must]

誤字ってますね。 🙅‍♂️

2022-11-09 15:40 UTC, piro0919 commented on .stylelintrc.json
> +    "stylelint-config-prettier-scssx`"
[imo]

これ初めて知りました。 👀 
`stylelint-config-prettier` と合わせて入れる必要があるか、確認してみてください。 👍

2022-11-09 16:26 UTC, ShSato4JPN commented on .stylelintrc.json
> +    "stylelint-config-prettier-scssx`"
かしこまりました👍
何か分かり次第共有いたします。

2022-11-09 16:26 UTC, ShSato4JPN commented on .stylelintrc.json
> +    "stylelint-config-prettier-scssx`"
すみません、気づきませんでした。。。
修正します😓

2022-11-09 16:26 UTC, ShSato4JPN commented on .stylelintrc.json
> +    "stylelint-config-standard-scss",
自分は[stylelint](https://stylelint.io/user-guide/get-started) のドキュメントを読んで、
```
  "extends": "stylelint-config-standard"
```
は、CSS 用のルール
```
  "extends": "stylelint-config-standard-scss"
```
は、SCSS 用のルール

と解釈していたのですが、

[stylelint-config-standard-scss](https://www.npmjs.com/package/stylelint-config-standard-scss) npm のドキュメントには、
> - extends the [stylelint-config-standard shared config](https://github.com/stylelint/stylelint-config-standard) and configures its rules for SCSS
> - extends the [stylelint-config-recommended-scss shared config](https://github.com/stylelint-scss/stylelint-config-recommended-scss)

と記述がありました。

ピロさんの仰る通り、```stylelint-config-standard-scss``` を入れるだけでいいのかもしれません🤔

2022-11-09 16:31 UTC, piro0919 commented on .stylelintrc.json
> +    "stylelint-config-standard-scss",
@ShSato4JPN 

なるほど？つまり CSS と SCSS の両方に対応しようとしている感じですかね。 🤔
個人的にはどちらか一方だけで十分かなーと思いますが、両方対応しようとしている理由ってなんですかね？ 👀

2022-11-09 16:33 UTC, ShSato4JPN commented on .stylelintrc.json
> +    "stylelint-config-prettier-scssx`"
[stylelint-config-prettier-scss/blob/main/src/index.js](https://github.com/prettier/stylelint-config-prettier-scss/blob/main/src/index.js) を見ると、```stylelint-config-prettier``` が extends されていました。
```stylelint-config-prettier-scss``` を入れる場合は、```stylelint-config-prettier``` を入れる必要はなさそうです😓

2022-11-09 16:41 UTC, ShSato4JPN commented on .stylelintrc.json
> +    "stylelint-config-standard-scss",
@piro0919 
css modules を使用する際、ファイル名が ```〇〇.module.css``` となりますので、
そのために CSS ファイル用のルールは入れたほうがいいのではと思い設定しました。

これは自分の直感でインストールしました。。

2022-11-09 16:42 UTC, piro0919 commented on .stylelintrc.json
> +    "stylelint-config-standard-scss",
@ShSato4JPN 

ディスコで話しましょーう。 😄

2022-11-11 14:16 UTC, ShSato4JPN commented
@piro0919 

[5e7f114](https://github.com/ShSato4JPN/world-of-zono/pull/19/commits/5e7f1140e2153980b33eb954b0090b40f095ff29)
ご指摘箇所を修正いたしました。
お手隙の際にご確認よろしくお願いいたします。

2022-11-12 04:57 UTC, ShSato4JPN commented
@piro0919 

レビュー前に申し訳ないです。
今回削除したパッケージを package.json から削除していませんでした。
修正します😭

2022-11-13 12:03 UTC, ShSato4JPN commented
@piro0919 

[b18f9dc](https://github.com/ShSato4JPN/world-of-zono/pull/19/commits/b18f9dcb3781f9bae931494598d38b5d2e38cd89)
package.json から不要なパッケージを削除いたしました。
お手隙の際にご確認のほどよろしくお願いいたします。

2022-11-13 14:55 UTC, piro0919 approved these changes
LGTM 👍

2022-11-13 15:00 UTC, ShSato4JPN commented
@piro0919

Thank you for your approval.

2022-11-13 15:00 UTC, merged