feat: add husky lint-staged commitlint
ShSato4JPN/world-of-zono pull request #35
Opened 2022-11-24 14:23 UTC by ShSato4JPN

close #26

2022-11-24 15:54 UTC, piro0919 requested changes

2022-11-24 15:54 UTC, piro0919 commented on .husky/pre-commit
> +npm run lint-staged
[imo]

わざわざ pacakge.json にスクリプトを追加する必要はなさそうですが、いかがでしょうか。 👀 
https://github.com/okonet/lint-staged#examples

2022-11-26 10:40 UTC, ShSato4JPN commented
@piro0919 
ご指摘ありがとうございます。
確かに、npx を使うことで package.json に lint-staged の設定がなくても動くようになりました！

[2c994af](https://github.com/ShSato4JPN/world-of-zono/pull/35/commits/2c994af6a922808035abb58e9cb021f93efe5c53)
お手隙の際にご確認よろしくお願いいたします。

2022-11-26 13:46 UTC, piro0919 approved these changes
LGTM 👍

2022-11-26 14:40 UTC, ShSato4JPN commented
@piro0919
Thank you for your approval.

2022-11-26 14:40 UTC, merged