feat: add sass setting
ShSato4JPN/world-of-zono pull request #42
Opened 2022-12-02 16:31 UTC by ShSato4JPN

close #41

2022-12-02 16:38 UTC, piro0919 requested changes

2022-12-02 16:38 UTC, piro0919 commented on .eslintrc.json
> +  "ignorePatterns": ["*.d.ts", "*.js"],
[must]

sass の導入に直接関係ないので、せめて何かしらの説明がほしいですね。 👀

2022-12-02 16:38 UTC, piro0919 commented on next.config.js
> +    includePaths: [path.join(__dirname, "styles")],
[must]

この設定が正しく動く保証がないのですが、大丈夫でしょうか？
現状使わないのであれば、むしろ設定しないほうが良いかもです。 😺 

rel https://github.com/ShSato4JPN/world-of-zono/issues/41#issuecomment-1335466198

2022-12-02 17:09 UTC, ShSato4JPN commented on next.config.js
> +    includePaths: [path.join(__dirname, "styles")],
@piro0919 
一応コミット前に npm scripts に設定しているコマンドは実行しているのですが、特にエラーは発生しませんでした🤔

> 現状使わないのであれば、むしろ設定しないほうが良いかもです。

設定しなくても動きました😮
てっきり設定が必須だと思っていました...。
ピロさんがおっしゃる通り、今回は設定しない方向でいきます！

2022-12-02 17:15 UTC, ShSato4JPN commented on .eslintrc.json
> +  "ignorePatterns": ["*.d.ts", "*.js"],
@piro0919 
説明不足で申し訳ないです。
こちらは、`next.config.js` に `const path = require("path");` を追加したところ、eslint にて以下のエラーが発生しました。
```
Require statement not part of import statement.eslint[@typescript-eslint/no-var-requires](https://typescript-eslint.io/rules/no-var-requires)
```
この回避策として、js ファイルを eslint 対象外にするためこちらの設定を追加しました。

2022-12-03 07:46 UTC, piro0919 commented
@ShSato4JPN 

全体的に実装が甘いので、PR を作成しなおしましょう。  😸

2022-12-03 07:46 UTC, closed without merging