feat: add contentful-typescript-codegen
ShSato4JPN/world-of-zono pull request #52
Opened 2022-12-14 13:48 UTC by ShSato4JPN

- install contentful-typescript-codegen
- add getContentfulEnvironment.js
- add getContentfulEnvironment.js to exclude in eslint

close #50

2022-12-14 14:29 UTC, piro0919 requested changes

2022-12-14 14:29 UTC, piro0919 commented on getContentfulEnvironment.js
> +  loadEnvConfig(process.env.PWD);
[imo]

省略形は避けたほうが無難ですね。 👀

2022-12-15 00:31 UTC, ShSato4JPN commented on getContentfulEnvironment.js
> +  loadEnvConfig(process.env.PWD);
ご指摘ありがとうございます!

初歩的な質問で申し訳ないのですが、省略形とはどのような形のことを言うのでしょうか😭

.env.local を使うのではなく、実行環境ごとに環境変数用意するべきだということでしょうか?

- .env.development
- .env.production

2022-12-15 07:09 UTC, piro0919 commented on getContentfulEnvironment.js
> +  loadEnvConfig(process.env.PWD);
@ShSato4JPN 

指摘がわかりづらかったですね。 🙇 
PWD のような省略表現を使うのではなく、もう少し最適な命名にしてほしいってだけです。 👍

2022-12-15 07:10 UTC, piro0919 commented
@ShSato4JPN 

今気づきましたけど、.gitignore が Next.js によって出力された内容になってないですね。 👀 
ちょっと原因はわからないですが、Issue だけ上げときますね

2022-12-15 13:26 UTC, ShSato4JPN commented on getContentfulEnvironment.js
> +  loadEnvConfig(process.env.PWD);
@piro0919 
`process.env.PWD` は自分で定義した環境変数ではなく、ワーキングディレクトリを取得する特殊なコードです！
（調べて存在を知りました☹️）

個人ブログですが参考になるかと...。
[プロセス実行時のワーキングディレクトリを取得する方法](https://mseeeen.msen.jp/how-to-get-pwd-on-nodejs/)

一方、Next の公式ドキュメントでは、`loadEnvConfig` の利用時に `process.cwd()` を使用していました。
`process.env.PWD` だと  windows 環境では undefined を返却することもあるらしいので、今回は Next のドキュメントを参考に `process.cwd()` を採用しようと思っております。よろしいでしょうか？
[Environment Variables](https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables)

2022-12-15 13:28 UTC, ShSato4JPN commented on getContentfulEnvironment.js
> +  loadEnvConfig(process.env.PWD);
@piro0919 
あと、`getContentfulEnvironment.js` に一箇所記述ミスがありましたので、そちらも同時に修正しようと思います。

2022-12-15 15:49 UTC, piro0919 commented on getContentfulEnvironment.js
> +  loadEnvConfig(process.env.PWD);
@ShSato4JPN 

>  process.env.PWD は自分で定義した環境変数ではなく、ワーキングディレクトリを取得する特殊なコードです！

 なるほどー。 👀 
ありがとうございます。 👍 

> 一方、Next の公式ドキュメントでは、loadEnvConfig の利用時に process.cwd() を使用していました。
process.env.PWD だと windows 環境では undefined を返却することもあるらしいので、今回は Next のドキュメントを参考に process.cwd() を採用しようと思っております。よろしいでしょうか？

まぁ、どっちでも良いかもですね。 😄 
おまかせしまーす。

2022-12-15 16:11 UTC, ShSato4JPN commented
@piro0919 

[1ca8189](https://github.com/ShSato4JPN/world-of-zono/pull/52/commits/1ca8189124b8cb6e70c0cfb25509d10832ae6407)

ソースコードを修正しましたので、お手隙の際にご確認よろしくお願いいたします。

2022-12-15 16:13 UTC, ShSato4JPN commented on getContentfulEnvironment.js
> +  loadEnvConfig(process.env.PWD);
@piro0919 

> @piro0919 あと、`getContentfulEnvironment.js` に一箇所記述ミスがありましたので、そちらも同時に修正しようと思います。

申し訳ないです。
こちらは自分の勘違いでした🙇‍♂️

2022-12-15 16:18 UTC, piro0919 approved these changes
LGTM 👍

2022-12-15 16:18 UTC, piro0919 commented on getContentfulEnvironment.js
> +  loadEnvConfig(projectDir);
[nits]

1行開けたほうが好みではありますね。 👀

2022-12-15 16:23 UTC, ShSato4JPN commented on getContentfulEnvironment.js
> +  loadEnvConfig(projectDir);
@piro0919 
一応 Next の公式ドキュメント通りの記述となっております。
今回はこれで行こうと思います！

2022-12-15 16:24 UTC, ShSato4JPN commented
@piro0919

Thank you for your approval.

2022-12-15 16:24 UTC, merged