feat: add globals.scss on app directory
ShSato4JPN/world-of-zono pull request #78
Opened 2023-03-05 08:39 UTC by ShSato4JPN

Close #77

2023-03-05 11:58 UTC, piro0919 requested changes
[must]

グローバルなスタイル以外の設定は省きましょうー。

2023-03-05 14:50 UTC, ShSato4JPN commented
@piro0919 
レビューありがとうございます🙇‍♂️

１回目のコミットで元々存在していた`globals.scss` を削除したのが失敗でした...。
レビューをしていただいたところ申し訳ないのですが、本ブランチをクローズしてもよろしいでしょうか。

2023-03-05 14:54 UTC, piro0919 commented
@ShSato4JPN 

？

swr の設定を削除してくれればそれで良いんですが…。

2023-03-05 15:32 UTC, ShSato4JPN commented
@piro0919 
ご指摘通り swr に関する設定を削除しました。

[23cc613](https://github.com/ShSato4JPN/world-of-zono/pull/78/commits/23cc6135413cce7bb1fc4ef735edff1024400a49)
お手隙の際にご確認のほどよろしくお願いいたします🙇‍♂️

2023-03-05 15:33 UTC, piro0919 commented
@ShSato4JPN 

fetcher も削除しましょうー。

2023-03-05 16:15 UTC, ShSato4JPN commented
@piro0919 
何度もレビューをお願いしてしまい申し訳ないです...。

[e552a71](https://github.com/ShSato4JPN/world-of-zono/pull/78/commits/e552a71eebc9ca1598387c6b20d582c750d51dbe)
fetcher を削除しました。
お手隙の際にご確認の程よろしくお願いいたします🙇‍♂️

2023-03-05 16:24 UTC, piro0919 commented
@ShSato4JPN 

再レビュー依頼お願いしますー。

2023-03-06 06:19 UTC, piro0919 approved these changes
LGTM 👍

2023-03-06 13:35 UTC, merged

2023-03-06 13:35 UTC, ShSato4JPN commented
@piro0919

Thank you for your approval.