feat: add global swr
ShSato4JPN/world-of-zono pull request #80
Opened 2023-03-06 14:50 UTC by ShSato4JPN

Close #79

2023-03-06 14:54 UTC, piro0919 requested changes
[must]

このコードだと正しく挙動するかわからないので、ある程度 api をつないでほしいですね。

2023-03-06 14:54 UTC, piro0919 commented on src/app/layout.tsx
> +import { SWRConfig } from "swr";
[imo]

SWRConfig を切り直したら layout コンポーネントがクライアントコンポーネントにする必要がなくなる気がしますね。 👀

2023-03-06 15:00 UTC, ShSato4JPN commented on src/app/layout.tsx
> +import { SWRConfig } from "swr";
なるほど。。。
出直してきます🙇‍♂️

2023-03-07 18:03 UTC, ShSato4JPN commented
@piro0919 
ふと思ったのですが、`layout` コンポーネント上の `SWRConfig` に `fetcher` を設定するので、
ブログ一覧画面では `fetcher` の実装が必要なくなると思います🤔
（`useSWRInfinite` に対する `fetcher` の設定が不要）

- [Global Configuration - SWR](https://swr.vercel.app/docs/global-configuration)

ピロさんのおっしゃる通り、グローバルの `swr` を設定しても動作確認ができないので、
ブログ一覧画面を作成する ISSUE にこちらの対応を含めて実装してもよろしいでしょうか？

2023-03-07 18:06 UTC, piro0919 commented
@ShSato4JPN 

まかせまーす。

2023-03-12 15:05 UTC, ShSato4JPN commented
#76 で対応したため、本ブランチは削除します。

2023-03-12 15:05 UTC, closed without merging