feat: add a rule to allow kebab case
ShSato4JPN/world-of-zono pull request #82
Opened 2023-03-08 14:14 UTC by ShSato4JPN

Close #81

2023-03-08 14:28 UTC, piro0919 requested changes
[must]

そもそも kebab-case を許容する理由ってなんですか？ 👀

2023-03-08 15:03 UTC, ShSato4JPN commented
@piro0919 
すみません、逆のこと言っていました😭
「`kebab-case` を許容する」ではなく、「`kebab-case` 以外を許容する」ですね...。

CSS Modules では `kebab-case` が使えなかったため、
Stylelint に `camel-case` を許容するルールを入れるつもりでいました。

申し訳ないのですが、一度ブランチを削除して再度レビューをしていただけないでしょうか🙇‍♂️

2023-03-09 02:27 UTC, piro0919 commented
@ShSato4JPN 

了解でーす。

2023-03-09 14:32 UTC, ShSato4JPN commented
ブランチ名とコミット内容が異なるためブランチを作り直します。

2023-03-09 14:32 UTC, closed without merging

2023-03-09 14:40 UTC, piro0919 commented
@ShSato4JPN 

ブランチ消しましょう−。