feat: add blog entry
ShSato4JPN/world-of-zono pull request #86
Opened 2023-03-14 14:22 UTC by ShSato4JPN

Close #85

2023-03-14 15:14 UTC, piro0919 requested changes

2023-03-14 15:14 UTC, piro0919 commented on src/app/api/entries/[id]/route.ts
> +    id: string;
[imo]

entryId とかにしたほうが保守性が高いですね。 👀 
パスから変えたほうが良いと思います。

2023-03-14 15:14 UTC, piro0919 commented on src/components/BlogEntry/index.tsx
> +        <Fragment key={index}>
[must]

Fragment いらないですね。

2023-03-14 15:14 UTC, piro0919 commented on src/components/BlogEntry/index.tsx
> +        <Fragment key={index}>
[imo]

key に index は振らないようにしましょうー。

2023-03-14 15:14 UTC, piro0919 commented on src/components/BlogEntry/index.tsx
> +            <div className={styles.categoryItem} key={index}>
[must]

なぜに key …？

2023-03-14 15:14 UTC, piro0919 commented on src/components/BlogEntry/index.tsx
> +            {data.fields.publishedAt.slice(0, 10)}
[must]

Date 型で扱いましょうー。
date-fns や dayjs の導入を検討しましょう。

2023-03-15 15:59 UTC, ShSato4JPN commented on src/components/BlogEntry/index.tsx
> +        <Fragment key={index}>
確かに、なくても問題ないものでした。。

2023-03-15 15:59 UTC, ShSato4JPN commented on src/components/BlogEntry/index.tsx
> +        <Fragment key={index}>
公式ドキュメントで理由を確認しました。
ご指摘ありがとうございます！

2023-03-15 16:02 UTC, ShSato4JPN commented on src/components/BlogEntry/index.tsx
> +            <div className={styles.categoryItem} key={index}>
すみません、こちらも公式ドキュメント見て key の意味を理解しました。
修正します！

2023-03-15 16:02 UTC, ShSato4JPN commented on src/components/BlogEntry/index.tsx
> +            {data.fields.publishedAt.slice(0, 10)}
かしこまりました！

2023-03-16 13:58 UTC, ShSato4JPN commented
@piro0919 
[e43053d](https://github.com/ShSato4JPN/world-of-zono/pull/86/commits/e43053de94d3fa9ce91acade59dab797ed9c3f1f)

指摘事項を修正しました。
お手隙の際に再度確認よろしくお願いいたします。

2023-03-16 14:55 UTC, piro0919 commented
@ShSato4JPN 

[e43053d](https://github.com/ShSato4JPN/world-of-zono/pull/86/commits/e43053de94d3fa9ce91acade59dab797ed9c3f1f) こういうコミットは NG です。 🙅‍♂️ 

あとから見返したときにコミットメッセージから内容が推測できないため、コミットの粒度として正しくないです。
一度 PR を close するので、正しい粒度でコミットを打ち直して上げ直しましょうー。

2023-03-16 14:55 UTC, closed without merging

2023-03-16 15:05 UTC, ShSato4JPN commented
@piro0919 
レビューありがとうございます🙇‍♂️
かしこまりました。